import type { MetadataRoute } from "next";

// PWA manifest - architecture plan §7. Installable on mobile home screens.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "MoVAI — סרטים חוקיים וחינמיים",
    short_name: "MoVAI",
    description: "מנוע גילוי סרטים חוקיים וחינמיים עם המלצות AI וחיפוש סמנטי.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#6d28d9",
    lang: "he",
    dir: "rtl",
    // Generated by app/icon.tsx (no static asset yet) - swap for real
    // 192/512 PNGs once brand assets exist; a 404'ing manifest icon breaks
    // "Add to Home Screen" silently, so this must never point at files that
    // don't exist in apps/web/public.
    icons: [{ src: "/icon", sizes: "32x32", type: "image/png" }]
  };
}
